---
name: idr0147-kuo-kidney3d/experimentA
version: 1

defaults:
  include: no
  type: string
  includeclient: yes
  visible: yes
  omitempty: yes

columns:

  - name: Characteristics [Strain]
    clientname: Strain
    include: yes

  - name: Characteristics [Organism Part]
    clientname: Organism Part
    include: yes

  - name: Comment [Organism Part Comments]
    clientname: Organism Part Comments
    include: yes

  - name: Characteristics [Age]
    clientname: Age
    include: yes

  - name: Experimental Condition [Genotype]
    clientname: Genotype
    include: yes

  - name: Comment [Image Description]
    clientname: Image Description
    include: yes

  - name: Comment [Image File Type]
    clientname: Image File Type
    include: yes


  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism]
          clientname: Organism
          include: yes



advanced:
  ignore_missing_primary_key: yes
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
