---
name: idr0147-kuo-kidney3d/experimentA
version: 1

defaults:
  include: no
  type: string
  includeclient: yes
  visible: yes
  omitempty: yes

columns:

  - name: Characteristics [Strain]
    clientname: Strain
    include: yes

  - name: Characteristics [Organism Part]
    clientname: Organism Part
    include: yes

  - name: Comment [Organism Part Comments]
    clientname: Organism Part Comments
    include: yes

  - name: Characteristics [Age]
    clientname: Age
    include: yes

  - name: Experimental Condition [Genotype]
    clientname: Genotype
    include: yes

  - name: Comment [Image Description]
    clientname: Image Description
    include: yes

  - name: Comment [Image File Type]
    clientname: Image File Type
    include: yes

  - name: ROI Original Dataset
    clientname: ROI Original Dataset
    include: yes

  - name: ROI X Coordinate
    clientname: ROI X Coordinate
    include: yes

  - name: ROI Y Coordinate
    clientname: ROI Y Coordinate
    include: yes

  - name: ROI Z Coordinate
    clientname: ROI Z Coordinate
    include: yes

  - name: ROI X Size
    clientname: ROI X Size
    include: yes

  - name: ROI Y Size
    clientname: ROI Y Size
    include: yes

  - name: ROI Z Size
    clientname: ROI Z Size
    include: yes

  - name: Comment [ROI Indexing]
    clientname: ROI Indexing Comment
    include: yes

  - name: Comment [ROI Dimensions]
    clientname: ROI Dimensions Comment
    include: yes

  - name: Glomeruli - number identified by machine learning
    clientname: Glomeruli - number identified by machine learning
    include: yes

  - name: Glomeruli - number of false positives
    clientname: Glomeruli - number of false positives
    include: yes

  - name: Glomeruli - number of false negatives estimated by sterology
    clientname: Glomeruli - number of false negatives estimated by sterology
    include: yes

  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism]
          clientname: Organism
          include: yes



advanced:
  ignore_missing_primary_key: yes
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
